export const NAV_LABELS = {
  dashboard: "Dashboard",
  profile: "Profile settings",
  users: "Users",
  divisions: "Divisions",
  /** @deprecated use divisions */
  vendors: "Vendors",
  mfgCompanies: "Manufacturers",
  qualityMaster: "Products",
  purchaseInvoices: "Purchases",
  customers: "Customers",
  salesBilling: "Sales & Billing",
  salesReturns: "Sales Returns",
  myCatalog: "My Catalog",
  orderCatalog: "Order Catalog",
  orders: "Orders",
  myOrders: "My Orders",
  prescriptions: "Prescriptions",
  divisionPayments: "Division Payments",
  /** @deprecated use divisionPayments */
  vendorPayments: "Vendor Payments",
  customerPayments: "Customer Payments",
  rolesAccess: "Roles & Access",
  changePassword: "Change password",
  reportInventory: "Inventory Reports",
  reportDayBook: "Day Book",
  reportLedger: "Ledger"
};

export const ROUTE_LABELS = {
  "/dashboard": NAV_LABELS.dashboard,
  "/profile": NAV_LABELS.profile,
  "/users": NAV_LABELS.users,
  "/divisions": NAV_LABELS.divisions,
  "/vendors": NAV_LABELS.vendors,
  "/mfg-companies": NAV_LABELS.mfgCompanies,
  "/quality-master": NAV_LABELS.qualityMaster,
  "/purchase-invoices": NAV_LABELS.purchaseInvoices,
  "/customers": NAV_LABELS.customers,
  "/sales-billing": NAV_LABELS.salesBilling,
  "/sales-returns": NAV_LABELS.salesReturns,
  "/my-catalog": NAV_LABELS.myCatalog,
  "/order-catalog": NAV_LABELS.orderCatalog,
  "/orders": NAV_LABELS.orders,
  "/my-orders": NAV_LABELS.myOrders,
  "/prescriptions": NAV_LABELS.prescriptions,
  "/division-payments": NAV_LABELS.divisionPayments,
  "/vendor-payments": NAV_LABELS.divisionPayments,
  "/customer-payments": NAV_LABELS.customerPayments,
  "/roles-access": NAV_LABELS.rolesAccess,
  "/change-password": NAV_LABELS.changePassword,
  "/first-login-change-password": NAV_LABELS.changePassword,
  "/reports/inventory": NAV_LABELS.reportInventory,
  "/reports/day-book": NAV_LABELS.reportDayBook,
  "/reports/ledger": NAV_LABELS.reportLedger,
  reports: "Reports"
};
